# Dual-language: PHP & Node.JS.
# https://github.com/travis-ci/travis-ci/issues/4090#issuecomment-184811689
language: php
php:
  - 7

git:
  depth: 8

before_install:
  - nvm install v4.4

install:
  - composer install
  - composer npm-install
  - composer eslint-config

script:
  - composer test
  - composer eslint

#End.
