# Dual-language ~ PHP & Node.JS.
# https://github.com/travis-ci/travis-ci/issues/4090#issuecomment-184811689

language: php

php: 7

git:
  depth: 8

# "$ npm --version // ERROR: npm is known not to run on Node.js v4.4.7"
before_install: nvm install v8.1

install:
  - composer install
  - composer npm-install

before_script:
  #- composer eslint-config # Not needed!
  - composer jshint-config
  - composer write-ignore-xml

script:
  - composer build
  - composer test
  - composer ci-test
  - npm run pa11y-ci
  - composer validate

after_script:
  - ls -al

notifications:
  email:
    recipients:
      - tesla-techsupport@open.ac.uk
      # - iet-ltt-support@open.ac.uk
    on_failure: always # default: always
  # slack: https://docs.travis-ci.com/user/notifications/#Configuring-Slack-notifications
  # webhooks:

# End.
